# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.4"

volumes:
  orderer1:
  orderer2:
  orderer3:
  peer0.committee:
  peer1.committee:
  peer0.voter:
  peer1.voter:
  peer0.adminops:
  peer1.adminops:

networks:
  evotebem:
    name: fabric_test

services:
  orderer1:
    container_name: orderer1
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=1100
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer1-MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:11100
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/orderer1/config.orderers/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/orderer1/config.orderers/tls/:/var/hyperledger/orderer/tls
      - orderer1:/var/hyperledger/production/orderer
    ports:
      - 1100:1100
      - 11100:11100
    networks:
      - evotebem

  orderer2:
    container_name: orderer2
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=1101
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer2-MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:11101
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/orderer2/config.orderers/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/orderer2/config.orderers/tls/:/var/hyperledger/orderer/tls
      - orderer2:/var/hyperledger/production/orderer
    ports:
      - 1101:1101
      - 11101:11101
    networks:
      - evotebem

  orderer3:
    container_name: orderer3
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=1102
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer3-MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:11102
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/orderer3/config.orderers/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/orderer3/config.orderers/tls/:/var/hyperledger/orderer/tls
      - orderer3:/var/hyperledger/production/orderer
    ports:
      - 1102:1102
      - 11102:11102
    networks:
      - evotebem

  peer0.committee:
    container_name: peer0.committee
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=evotebem
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.committee
      - CORE_PEER_ADDRESS=peer0.committee:4444
      - CORE_PEER_LISTENADDRESS=0.0.0.0:4444
      - CORE_PEER_CHAINCODEADDRESS=peer0.committee:4445
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:4445
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.committee:4454
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.committee:4444
      - CORE_PEER_LOCALMSPID=committeemsp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:14444
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_PVTDATA_PUSHACKTIMEOUT=12s
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:4446
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/committee/peers/peer0.committee/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/committee/peers/peer0.committee/tls:/etc/hyperledger/fabric/tls
      - peer0.committee:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 4444:4444
      - 14444:14444
    networks:
      - evotebem

  peer1.committee:
    container_name: peer1.committee
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=evotebem
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.committee
      - CORE_PEER_ADDRESS=peer1.committee:4454
      - CORE_PEER_LISTENADDRESS=0.0.0.0:4454
      - CORE_PEER_CHAINCODEADDRESS=peer1.committee:4455
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:4455
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.committee:4444
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.committee:4454
      - CORE_PEER_LOCALMSPID=committeemsp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:14454
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_PVTDATA_PUSHACKTIMEOUT=12s
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:4456
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/committee/peers/peer1.committee/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/committee/peers/peer1.committee/tls:/etc/hyperledger/fabric/tls
      - peer1.committee:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 4454:4454
      - 14454:14454
    networks:
      - evotebem

  peer0.voter:
    container_name: peer0.voter
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=evotebem
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.voter
      - CORE_PEER_ADDRESS=peer0.voter:5555
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5555
      - CORE_PEER_CHAINCODEADDRESS=peer0.voter:5556
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5556
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.voter:5565
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.voter:5555
      - CORE_PEER_LOCALMSPID=votermsp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:15555
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_PVTDATA_PUSHACKTIMEOUT=12s
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:5557
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/voter/peers/peer0.voter/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/voter/peers/peer0.voter/tls:/etc/hyperledger/fabric/tls
      - peer0.voter:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 5555:5555
      - 15555:15555
    networks:
      - evotebem

  peer1.voter:
    container_name: peer1.voter
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=evotebem
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.voter
      - CORE_PEER_ADDRESS=peer1.voter:5565
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5565
      - CORE_PEER_CHAINCODEADDRESS=peer1.voter:5566
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5566
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.voter:5555
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.voter:5565
      - CORE_PEER_LOCALMSPID=votermsp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:15565
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_PVTDATA_PUSHACKTIMEOUT=12s
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:5567
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/voter/peers/peer1.voter/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/voter/peers/peer1.voter/tls:/etc/hyperledger/fabric/tls
      - peer1.voter:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 5565:5565
      - 15565:15565
    networks:
      - evotebem

  peer0.adminops:
    container_name: peer0.adminops
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=evotebem
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.adminops
      - CORE_PEER_ADDRESS=peer0.adminops:6666
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6666
      - CORE_PEER_CHAINCODEADDRESS=peer0.adminops:6667
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6667
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.adminops:6676
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.adminops:6666
      - CORE_PEER_LOCALMSPID=adminopsmsp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:16666
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_PVTDATA_PUSHACKTIMEOUT=12s
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:6668
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/adminops/peers/peer0.adminops/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/adminops/peers/peer0.adminops/tls:/etc/hyperledger/fabric/tls
      - peer0.adminops:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 6666:6666
      - 16666:16666
    networks:
      - evotebem

  peer1.adminops:
    container_name: peer1.adminops
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=evotebem
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.adminops
      - CORE_PEER_ADDRESS=peer1.adminops:6676
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6676
      - CORE_PEER_CHAINCODEADDRESS=peer1.adminops:6676
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6677
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.adminops:6666
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.adminops:6676
      - CORE_PEER_LOCALMSPID=adminopsmsp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:16676
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_PVTDATA_PUSHACKTIMEOUT=12s
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:6678
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/adminops/peers/peer1.adminops/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/adminops/peers/peer1.adminops/tls:/etc/hyperledger/fabric/tls
      - peer1.adminops:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 6676:6676
      - 16676:16676
    networks:
      - evotebem

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.committee
      - peer1.committee
      - peer0.voter
      - peer1.voter
      - peer0.adminops
      - peer1.adminops
    networks:
      - evotebem



